### PR TITLE
Add option to set initial search and delete delay values

### LINKED ISSUE #128: [Question] New Discord rate limiting
I have been an avid user of this script for a while now. It's great and does everything I need.

I ran it for the first time in a while today and found I am being rate limited to at minimum 6000ms per deletion by Discord.

Is this a new problem? It practically breaks the script as it takes hours to delete a few hundred messages.

### PR DESCRIPTION
**Pull request by Galaxyzd**
Fixes #128 and #118

---
This change is [Reviewable](https://reviewable.io/reviews/victornpb/deletediscordmessages/129)

### CODE REVIEW

**Comment by Galaxyzd** [comment]
From testing 1000ms seems like a good delay. For me the API has not complained yet with 1000ms set for both. Perhaps you could change the default delay to 1000ms instead.

**Comment by Galaxyzd** [comment]
After a bit more careful testing, search delay does not seem nearly as impactful as delete delay. Documentation and code has been updated accordingly.

**Comment by ExillustX** [comment]
Just tested this for hours and it works perfectly. Also a delete delay value of 800ms works fine without triggering any rate-limits. Hoping this PR gets merged.

**Review by ExillustX — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/victornpb/deletediscordmessages/129)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by whalehub** [comment]
@victornpb requesting review

**Review by victornpb — APPROVED** [review]

**Pull request merged**
