### PR TITLE
Code style changes

### PR DESCRIPTION
**Pull request by AstroOrbis**
This change is [Reviewable](https://reviewable.io/reviews/victornpb/deletediscordmessages/269)

### CODE REVIEW

**Comment by AstroOrbis** [comment]
I used Prettier if anyone is curious

**Comment by victornpb** [comment]
Thanks for the effort but I don't think this is an improvement.

The code is currently formated using VScode TS provider, I use prettier for other projects but I think userscripts are a special case, I'm trying to balance readability and total size, and the default 80col prettier rule chops the code into tiny vertical pieces way to aggressively.

It increased the script by ~200 lines, which is not a problem by itself but, it also made the code LESS readable IMO.
I'll give a few examples why I don't agree with the style choices:

Unnecessary line break
image

Unnecessary asymmetry
image

This is not more readable than before
image

All of those are supposed to be 1-liners, prettier like to turn those into broken noodles 
image
image

**Comment by AstroOrbis** [comment]
Wow, this is the most detailed response I've ever gotten in a GitHub pull request. Thanks for the feedback!

**Comment by victornpb** [comment]
You're welcome 😊

**Pull request closed without merging**
